import type { CertQuestion } from "./cert-types";

// Scenario 4: Developer Productivity with Claude
export const DEVELOPER_PRODUCTIVITY_QUESTIONS: CertQuestion[] = [
	{
		id: "dp-q1",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "easy",
		stem: "You need to find all test files in a large React codebase that follow the naming pattern *.test.tsx or *.test.ts. The codebase has 500+ files across 30+ directories. What tool should the agent use?",
		choices: [
			{ key: "A", text: "Grep with pattern --include='*.test.*'" },
			{ key: "B", text: "Glob with pattern **/*.test.{ts,tsx}" },
			{ key: "C", text: "Read all files in src/ to identify test files" },
			{ key: "D", text: "Bash command find . -name '*.test.*'" },
		],
		correct: "B",
		explanation:
			"Glob is designed for file path pattern matching. **/*.test.{ts,tsx} directly matches the convention. Grep searches contents (slower); Read is overkill; Bash find is functional but not the primary Claude Code tool.",
		distractorRationales: {
			A: "Grep is for content search, not file path patterns.",
			C: "Bulk Read is wildly inefficient.",
			D: "Bash find works but isn't the canonical Claude Code tool for this.",
		},
		studyTags: ["Glob", "file-paths", "Task-2.5"],
	},
	{
		id: "dp-q2",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A file contains 12 lines with `const X = null;` and the agent needs to change only one specific line (line 42) to `const X = undefined;`. The anchor 'const X = null;' is not unique. What should the agent do?",
		choices: [
			{ key: "A", text: "Use Edit with anchor 'const X = null;' and hope it matches the right line." },
			{ key: "B", text: "Use Read, identify the specific line, use Edit with more unique surrounding text." },
			{ key: "C", text: "Use Bash sed to replace line 42." },
			{ key: "D", text: "Use Read, then Write to overwrite the entire file." },
		],
		correct: "B",
		explanation:
			"Task 2.5: when Edit's anchor isn't unique, Read first, then extend the anchor with surrounding context until it's unique. Edit with that anchor is surgical and correct.",
		distractorRationales: {
			A: "Edit with non-unique anchor will fail or edit the wrong line.",
			C: "Bash sed isn't the canonical Claude Code mechanism.",
			D: "Read + Write is the documented fallback only when no unique anchor can be found in context.",
		},
		studyTags: ["Edit", "anchor-uniqueness", "Task-2.5"],
	},
	{
		id: "dp-q3",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A team uses Jira for issue tracking and GitHub for repos. The Jira server is not yet officially supported; the team is evaluating a beta MCP implementation. Where should the Jira MCP be configured?",
		choices: [
			{ key: "A", text: ".mcp.json in the project root" },
			{ key: "B", text: "~/.claude.json in the user's home directory" },
			{ key: "C", text: "A shared CLAUDE.md file with MCP setup instructions" },
			{ key: "D", text: "A Git submodule with the MCP server code" },
		],
		correct: "B",
		explanation:
			"Beta/experimental servers go in user-level config. Move to .mcp.json once team-validated.",
		distractorRationales: {
			A: "Project config is for stable, team-adopted servers.",
			C: "CLAUDE.md is for code conventions, not MCP setup.",
			D: "Git submodule doesn't directly configure MCP.",
		},
		studyTags: ["mcp-config", "experimental", "Task-2.4"],
	},
	{
		id: "dp-q4",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "easy",
		stem: "A .mcp.json file needs to include a Jira API token. The team wants to ensure tokens are not stored in version control. Which is the correct pattern?",
		choices: [
			{ key: "A", text: "'JIRA_TOKEN': 'jira_token_abc123...'" },
			{ key: "B", text: "'JIRA_TOKEN': '${JIRA_TOKEN}'" },
			{ key: "C", text: "'JIRA_TOKEN': 'process.env.JIRA_TOKEN'" },
			{ key: "D", text: "'JIRA_TOKEN': '@env:JIRA_TOKEN'" },
		],
		correct: "B",
		explanation:
			".mcp.json supports ${ENV_VAR} expansion. Developers set 'export JIRA_TOKEN=...' in their shell.",
		distractorRationales: {
			A: "Hardcoded token, exposed in VCS.",
			C: "Not valid in JSON.",
			D: "Not the correct syntax.",
		},
		studyTags: ["env-var-expansion", "secrets", "Task-2.4"],
	},
	{
		id: "dp-q5",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A development team wants Claude Code to be aware of all available Jira projects (INFRA, FRONTEND, BACKEND, OPS) without making a tool call every time. What should the MCP server expose?",
		choices: [
			{ key: "A", text: "A tool list_projects that returns the list" },
			{ key: "B", text: "A resource jira://projects that returns ['INFRA', 'FRONTEND', 'BACKEND', 'OPS']" },
			{ key: "C", text: "A prompt hint that lists the projects" },
			{ key: "D", text: "A CLAUDE.md file with the project list" },
		],
		correct: "B",
		explanation:
			"Resources expose read-only data catalogs; agents can read them upfront without using a tool call each time. Tools are for actions or dynamic queries.",
		distractorRationales: {
			A: "Tool wastes a tool call for static data.",
			C: "Prompts are for system instructions, not data.",
			D: "CLAUDE.md is for code conventions, not external service data.",
		},
		studyTags: ["mcp-resources", "catalogs", "Task-2.4"],
	},
	{
		id: "dp-q6",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A team's MCP server includes a tool search_github_issues with description 'Search for issues.' The agent often ignores this tool and uses Grep instead. Most effective fix?",
		choices: [
			{ key: "A", text: "Disable Grep in the agent's tool list" },
			{ key: "B", text: "Add few-shot examples showing when to use the tool" },
			{ key: "C", text: "Expand the tool description to include input formats, output structure, and explicit 'Use this, not Grep, because...' guidance" },
			{ key: "D", text: "Rename the tool to find_github_issues_by_label" },
		],
		correct: "C",
		explanation:
			"Tool descriptions are the primary signal for tool selection. Expand with input/output specs and explicit alternatives.",
		distractorRationales: {
			A: "Disabling Grep removes a useful tool for code search.",
			B: "Few-shot helps; fixing the root cause (description) is more effective.",
			D: "Renaming alone doesn't clarify the distinction.",
		},
		studyTags: ["tool-descriptions", "Task-2.1"],
	},
	{
		id: "dp-q7",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.4"],
		mode: "canonical",
		difficulty: "easy",
		stem: "A team uses both Jira and a proprietary issue tracker called 'InternalTrak.' Official MCP exists for Jira; no public MCP for InternalTrak. Which approach minimizes maintenance burden?",
		choices: [
			{ key: "A", text: "Build custom MCP servers for both" },
			{ key: "B", text: "Use the official Jira MCP server; build a custom MCP for InternalTrak" },
			{ key: "C", text: "Use Bash scripts for both" },
			{ key: "D", text: "Disable issue tracking integration" },
		],
		correct: "B",
		explanation:
			"Use community/official MCP servers for standard integrations to avoid maintenance. Reserve custom MCP for genuinely team-specific workflows.",
		distractorRationales: {
			A: "Building custom Jira MCP is unnecessary maintenance.",
			C: "Bash scripts are less integrated and don't expose tools.",
			D: "Removes valuable functionality.",
		},
		studyTags: ["community-mcp", "custom-mcp", "Task-2.4"],
	},
	{
		id: "dp-q8",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "An engineer asks: 'I need to understand how user authentication works in this codebase.' Most efficient exploration strategy?",
		choices: [
			{ key: "A", text: "Read all files in src/auth/ directory, then read all importing files" },
			{ key: "B", text: "Grep for authenticate/login/token patterns; Read entry point (e.g., src/auth/index.ts); identify exported functions; Grep each to find callers; Read only calling files" },
			{ key: "C", text: "Bash 'find src -name *.ts | head -20' and read them" },
			{ key: "D", text: "Spawn a subagent to 'understand authentication' and return a summary" },
		],
		correct: "B",
		explanation:
			"Incremental discovery (Grep → Read → Grep → Read) builds understanding efficiently. Bulk reads waste context; subagent hides details engineer needs.",
		distractorRationales: {
			A: "Bulk reading wastes context.",
			C: "Random sample misses relevant files.",
			D: "Subagents are for discovery isolation, not primary investigation when engineer wants detail.",
		},
		studyTags: ["incremental-discovery", "Grep-first", "Task-2.5"],
	},
	{
		id: "dp-q9",
		scenario: "developer-productivity",
		domain: "D3",
		tasks: ["1.7", "5.4"],
		mode: "canonical",
		difficulty: "hard",
		stem: "An engineer analyzed a codebase yesterday with claude --resume migration-analysis. Today, the team merged 15 commits affecting 8 files the engineer analyzed. How to continue?",
		choices: [
			{ key: "A", text: "Use claude --resume migration-analysis immediately" },
			{ key: "B", text: "Start a fresh session; pass a summary of yesterday's findings; inform Claude that specific files changed" },
			{ key: "C", text: "Use claude --resume but Grep changed files to re-validate prior analysis" },
			{ key: "D", text: "Fork the prior session" },
		],
		correct: "B",
		explanation:
			"Stale tool results are unreliable. New session + structured summary is safer than resuming with potentially outdated analysis.",
		distractorRationales: {
			A: "Resume includes stale tool results; prior analysis is now incorrect.",
			C: "Manual comparison is error-prone.",
			D: "Fork is for comparing approaches, not handling changed files.",
		},
		studyTags: ["session-resume", "stale-results", "Task-1.7"],
	},
	{
		id: "dp-q10",
		scenario: "developer-productivity",
		domain: "D3",
		tasks: ["3.4"],
		mode: "canonical",
		difficulty: "easy",
		stem: "Engineer provides a stack trace: 'Error at line 127 in utils/validate.ts: TypeError: expected string, got undefined.' The error is in a single function with a clear fix (null check). Plan mode or direct execution?",
		choices: [
			{ key: "A", text: "Plan mode to explore the codebase first" },
			{ key: "B", text: "Direct execution; the scope is clear" },
			{ key: "C", text: "Plan mode first, then direct execution" },
			{ key: "D", text: "Use an Explore subagent" },
		],
		correct: "B",
		explanation:
			"Direct execution for single-file, clear-scope, low-risk fixes.",
		distractorRationales: {
			A: "Overkill for a one-line fix.",
			C: "Combines both unnecessarily.",
			D: "Subagent exploration is unnecessary here.",
		},
		studyTags: ["direct-execution", "plan-mode", "Task-3.4"],
	},
	{
		id: "dp-q11",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "config.ts has these three lines: `export const LOG_LEVEL = 'info'; export const LOG_FORMAT = 'info'; export const LOG_HANDLER = 'file';`. The agent needs to change LOG_LEVEL to 'debug'. Anchor `= 'info';` appears twice. Correct approach?",
		choices: [
			{ key: "A", text: "Use Edit with anchor `const LOG_LEVEL = 'info';`" },
			{ key: "B", text: "Use Edit with anchor `export const LOG_LEVEL = 'info';`" },
			{ key: "C", text: "Use Read, then Write (overwrite entire file)" },
			{ key: "D", text: "Use Bash sed" },
		],
		correct: "A",
		explanation:
			"`const LOG_LEVEL = 'info';` is unique because the variable name disambiguates it. Minimal sufficient anchor is the canonical answer.",
		distractorRationales: {
			B: "Also unique but longer than necessary.",
			C: "Read + Write is the fallback when no unique anchor exists. Here, one does.",
			D: "Bash sed isn't the canonical Claude Code mechanism.",
		},
		studyTags: ["Edit", "anchor-extension", "Task-2.5"],
	},
	{
		id: "dp-q12",
		scenario: "developer-productivity",
		domain: "D1",
		tasks: ["1.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A coordinator agent discovers: 'Authentication is in src/auth/oauth.ts and src/auth/jwt.ts.' Coordinator spawns subagent: 'Find all places in the codebase that use authentication.' Subagent returns 'No authentication usage found.' Likely cause?",
		choices: [
			{ key: "A", text: "The codebase doesn't use authentication" },
			{ key: "B", text: "The subagent lacks context about the files where authentication is implemented" },
			{ key: "C", text: "Grep is disabled in the subagent" },
			{ key: "D", text: "The Explore subagent should have been used" },
		],
		correct: "B",
		explanation:
			"Subagent context is isolated. Coordinator must explicitly pass file locations: 'Authentication is in oauth.ts and jwt.ts. Find all callers.'",
		distractorRationales: {
			A: "Unlikely if coordinator already found it.",
			C: "Grep isn't typically disabled.",
			D: "Different subagent type wouldn't help; missing context is the issue.",
		},
		studyTags: ["subagent-isolation", "context-passing", "Task-1.3"],
	},
	{
		id: "dp-q13",
		scenario: "developer-productivity",
		domain: "D5",
		tasks: ["5.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "After 80 messages, engineer asks: 'Which database adapter is used in the ORM layer?' Claude responds: 'Based on the typical patterns, I believe it's likely either PostgreSQL or MySQL.' Most effective fix?",
		choices: [
			{ key: "A", text: "Grep for 'postgres' or 'mysql' to get the answer" },
			{ key: "B", text: "Start a new session with a summary of the 80-message exploration" },
			{ key: "C", text: "Run /compact to consolidate findings, then ask again" },
			{ key: "D", text: "Use a subagent to find the database adapter" },
		],
		correct: "C",
		explanation:
			"Vague 'typical patterns' phrasing is the textbook symptom of context degradation in extended sessions. /compact is the canonical first response.",
		distractorRationales: {
			A: "Targeted Grep finds the answer but doesn't address the degradation root cause.",
			B: "/compact preserves the structured summary while shedding verbose tool output.",
			D: "Subagents are for verbose discovery, not fixing main session degradation.",
		},
		studyTags: ["compact", "context-degradation", "Task-5.4"],
	},
	{
		id: "dp-q14",
		scenario: "developer-productivity",
		domain: "D2",
		tasks: ["2.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A team has search_codebase (Grep wrapper, 50 files) and semantic_search (MCP, embeddings, 500 files with semantic understanding). Agent usually picks search_codebase even when semantic search would be more effective. Best first step?",
		choices: [
			{ key: "A", text: "Disable search_codebase" },
			{ key: "B", text: "Improve the semantic_search tool description to highlight semantic matching, vectorized search, broader scope, and explicit 'Use this for intent-based queries' guidance" },
			{ key: "C", text: "Add few-shot examples of when to use semantic_search" },
			{ key: "D", text: "Rename search_codebase to grep_wrapper" },
		],
		correct: "B",
		explanation:
			"Tool descriptions are the primary signal. Expand with semantics, scope, and differentiation.",
		distractorRationales: {
			A: "Disables a useful tool.",
			C: "Few-shot helps; fixing descriptions is more foundational.",
			D: "Renaming alone doesn't clarify purpose.",
		},
		studyTags: ["tool-descriptions", "differentiation", "Task-2.1"],
	},
	{
		id: "dp-q15",
		scenario: "developer-productivity",
		domain: "D3",
		tasks: ["3.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Project has instructions for test organization in .claude/CLAUDE.md at project root. New developer clones repo, opens in Claude Code, doesn't see test organization rules. Most likely cause?",
		choices: [
			{ key: "A", text: "Developer is using a personal CLAUDE.md that overrides the project-level one" },
			{ key: "B", text: "CLAUDE.md is not automatically loaded from project root; must be explicitly imported" },
			{ key: "C", text: "Developer hasn't set up shell environment correctly" },
			{ key: "D", text: "CLAUDE.md is ignored because it's in .claude/" },
		],
		correct: "A",
		explanation:
			"CLAUDE.md hierarchy: user → project → directory. User-level can take precedence and hide project rules.",
		distractorRationales: {
			B: ".claude/CLAUDE.md at project root IS automatically loaded.",
			C: "Shell env doesn't affect CLAUDE.md loading.",
			D: ".claude/ is the correct location for project-scoped config.",
		},
		studyTags: ["CLAUDE.md-hierarchy", "Task-3.1"],
	},
	{
		id: "dp-q16",
		scenario: "developer-productivity",
		domain: "D1",
		tasks: ["1.7"],
		mode: "canonical",
		difficulty: "medium",
		stem: "An engineer wants to test Strategy A (OAuth via external) vs Strategy B (custom JWT internal). Best way to compare?",
		choices: [
			{ key: "A", text: "Implement A, then manually implement B in a separate session" },
			{ key: "B", text: "Main agent analyzes the codebase, then spawns two fork sessions (or subagents): one to implement A, one to implement B. Compare results." },
			{ key: "C", text: "Implement both sequentially in the same session" },
			{ key: "D", text: "Use plan mode to design both approaches, then manually decide" },
		],
		correct: "B",
		explanation:
			"fork_session allows divergent exploration from a shared codebase baseline. Each fork independently implements and tests its strategy.",
		distractorRationales: {
			A: "Manual comparison is error-prone, context-heavy.",
			C: "Sequential in one session risks bias from first strategy.",
			D: "Plan mode is useful for design, but fork_session enables parallel implementation.",
		},
		studyTags: ["fork_session", "divergent-approaches", "Task-1.7"],
	},
	{
		id: "dp-q17",
		scenario: "developer-productivity",
		domain: "D5",
		tasks: ["5.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "After 60 messages exploring with 5+ bulk Reads of entire src/ contents, Claude responds vaguely: 'I believe it uses one of the common adapters like SQLAlchemy or Prisma, based on typical patterns.' Root cause and best mitigation?",
		choices: [
			{ key: "A", text: "Database adapter isn't in the codebase; Claude is guessing." },
			{ key: "B", text: "Context degradation from verbose Read outputs; specific details are lost. Mitigation: /compact or start fresh with a summary of prior findings." },
			{ key: "C", text: "Glob should have been used instead of Read." },
			{ key: "D", text: "Codebase uses multiple adapters and Claude is uncertain." },
		],
		correct: "B",
		explanation:
			"Vague language ('typical patterns') is the symptom of context degradation. Mitigate with /compact or fresh + summary.",
		distractorRationales: {
			A: "Specific details are in the codebase; the issue is degradation.",
			C: "Glob finds files; the issue is Read output accumulation.",
			D: "Multiple adapters might exist, but the symptom points to degradation.",
		},
		studyTags: ["context-degradation", "vague-language", "Task-5.4"],
	},
];
