import type { CertQuestion } from "./cert-types";

// Scenario 5: Claude Code for Continuous Integration (CI/CD)
export const CICD_QUESTIONS: CertQuestion[] = [
	{
		id: "ci-q1",
		scenario: "ci-cd",
		domain: "D3",
		tasks: ["3.6"],
		mode: "canonical",
		difficulty: "easy",
		stem: "Claude Code is integrated into a GitHub Actions workflow. The step `claude 'Review the changes for bugs'` hangs indefinitely. Most effective fix?",
		choices: [
			{ key: "A", text: "Add the -p flag to the invocation." },
			{ key: "B", text: "Set the CLAUDE_HEADLESS=true environment variable before running claude." },
			{ key: "C", text: "Pipe /dev/null into claude: `claude '...' < /dev/null`." },
			{ key: "D", text: "Use the --batch flag." },
		],
		correct: "A",
		explanation:
			"Task 3.6 explicitly requires the -p / --print flag for non-interactive mode. Tells Claude to process input and exit cleanly without waiting for follow-up.",
		distractorRationales: {
			B: "CLAUDE_HEADLESS doesn't exist.",
			C: "Piping /dev/null doesn't prevent hanging on internal decisions.",
			D: "--batch flag doesn't exist; the batch API is a separate system.",
		},
		studyTags: ["-p-flag", "non-interactive", "Task-3.6"],
	},
	{
		id: "ci-q2",
		scenario: "ci-cd",
		domain: "D3",
		tasks: ["3.6"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A CI workflow reviews PRs and posts findings as GitHub comments. Currently, output is prose: 'In src/login.ts line 47, the fetch() call doesn't have error handling...' Parsing is fragile. Which approach best enables reliable automated commenting?",
		choices: [
			{ key: "A", text: "Ask Claude to format findings as 'FILE:LINE: ISSUE' on each line." },
			{ key: "B", text: "Use --output-format json and --json-schema with a defined schema for findings." },
			{ key: "C", text: "Ask Claude to output findings as CSV with file, line, issue columns." },
			{ key: "D", text: "Require findings as Markdown tables and parse the table." },
		],
		correct: "B",
		explanation:
			"Task 3.6 requires --output-format json and --json-schema for CI. Validates structure, eliminates parse ambiguity, supports detected_pattern.",
		distractorRationales: {
			A: "Prose parsing is fragile.",
			C: "CSV is unstructured (no type validation, no schema enforcement).",
			D: "Markdown table parsing is fragile and doesn't validate types.",
		},
		studyTags: ["json-schema", "output-format", "Task-3.6"],
	},
	{
		id: "ci-q3",
		scenario: "ci-cd",
		domain: "D3",
		tasks: ["1.6", "4.6"],
		mode: "canonical",
		difficulty: "hard",
		stem: "A 14-file PR review flags inconsistent severity (null-check 'high' in file 1, 'low' in file 8) and misses cross-file data-flow issues. Root cause and fix?",
		choices: [
			{ key: "A", text: "Context window too small; use Claude 3 Opus instead of Sonnet." },
			{ key: "B", text: "Run the review 3 times and report only findings present in all 3 runs to reduce noise." },
			{ key: "C", text: "Single-pass review of all 14 files at once causes attention dilution. Decompose into per-file local passes (each file independent) followed by a separate cross-file integration pass." },
			{ key: "D", text: "Ask developers to split large PRs into smaller ones (max 5 files per PR)." },
		],
		correct: "C",
		explanation:
			"Task 1.6 + 4.6: per-file passes for local issues + integration pass for cross-file data flow.",
		distractorRationales: {
			A: "Both Sonnet and Opus have 200K tokens. Bigger context doesn't fix dilution.",
			B: "Consensus suppresses real bugs that are missed in some runs.",
			D: "Shifts burden to developers; the review system should be multi-pass.",
		},
		studyTags: ["multi-pass", "attention-dilution", "Task-1.6", "Task-4.6"],
	},
	{
		id: "ci-q4",
		scenario: "ci-cd",
		domain: "D4",
		tasks: ["4.1", "4.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Code review findings: 45% real bugs, 55% false positives (style flagged as bug, missing JSDoc as 'incomplete implementation'). Prompt says 'Be conservative — only report things you're confident about.' Most effective fix?",
		choices: [
			{ key: "A", text: "Add a confidence threshold: 'Report only if confidence > 80%.'" },
			{ key: "B", text: "Define explicit criteria with concrete examples: 'Report as BUG (high): uncaught promise rejection. Example: ... → REPORT'; 'DO NOT REPORT: missing JSDoc, style inconsistencies' with 2-3 worked examples per severity." },
			{ key: "C", text: "Run the review twice and report only findings in both runs." },
			{ key: "D", text: "Disable the entire 'style' category by removing style-related examples." },
		],
		correct: "B",
		explanation:
			"Task 4.1: explicit criteria > vague instructions. Task 4.2: few-shot with concrete examples beats general instructions.",
		distractorRationales: {
			A: "Self-reported confidence is poorly calibrated.",
			C: "Doesn't reduce FP; increases noise.",
			D: "Too blunt; refine criteria with examples that show the boundary.",
		},
		studyTags: ["explicit-criteria", "few-shot", "Task-4.1", "Task-4.2"],
	},
	{
		id: "ci-q5",
		scenario: "ci-cd",
		domain: "D4",
		tasks: ["4.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Two workflows: (1) Pre-merge checks (block merge, SLA < 5 minutes), (2) Overnight tech-debt reports (next morning). Should the team use Message Batches API for both?",
		choices: [
			{ key: "A", text: "Yes, batch is generally faster and cheaper." },
			{ key: "B", text: "No. Pre-merge checks should use synchronous API. Overnight reports can use batch API (cost savings acceptable, latency tolerant)." },
			{ key: "C", text: "Use batch for pre-merge but implement a 2-minute timeout fallback to sync API." },
			{ key: "D", text: "Batch supports ordered retrieval via custom_id sorting, so it's appropriate for both if you sort results." },
		],
		correct: "B",
		explanation:
			"Task 4.5: Batch API has no latency SLA (up to 24 hours). Pre-merge needs sync; overnight tolerates batch.",
		distractorRationales: {
			A: "Batch is NOT faster; no SLA, can take 24 hours.",
			C: "Adds unnecessary complexity. Decide upfront.",
			D: "custom_id is for correlation, not ordering. Doesn't make batch appropriate for blocking workflows.",
		},
		studyTags: ["batch-vs-sync", "Task-4.5"],
	},
	{
		id: "ci-q6",
		scenario: "ci-cd",
		domain: "D4",
		tasks: ["4.6"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Developer uses Claude Code to generate a login handler, then asks Claude in the same session to review it. Review flags 2 bugs. An independent Claude instance reviewing the same code flags 7 bugs. Why does the independent instance find more issues?",
		choices: [
			{ key: "A", text: "Larger context window." },
			{ key: "B", text: "Lacks generation reasoning context; avoids bias where the generator is less likely to question its own code." },
			{ key: "C", text: "Different model (Sonnet instead of Opus)." },
			{ key: "D", text: "Ran the review twice while the first ran it once." },
		],
		correct: "B",
		explanation:
			"Task 4.6: same-session retains generation reasoning, making the model reluctant to criticize. Fresh context eliminates this bias.",
		distractorRationales: {
			A: "Both have the same context window.",
			C: "Model version isn't the variable; session context is.",
			D: "No evidence of running twice.",
		},
		studyTags: ["session-isolation", "Task-4.6"],
	},
	{
		id: "ci-q7",
		scenario: "ci-cd",
		domain: "D3",
		tasks: ["3.6"],
		mode: "canonical",
		difficulty: "medium",
		stem: "PR is reviewed; Claude flags 5 bugs. Developer fixes 3 and pushes. Team runs review again WITHOUT including prior findings in the prompt. Likely outcome?",
		choices: [
			{ key: "A", text: "Correctly reports only the 2 unfixed bugs." },
			{ key: "B", text: "Re-flags the 3 fixed bugs, creating duplicate comments." },
			{ key: "C", text: "Misses all bugs because context is fresh." },
			{ key: "D", text: "Flags all 5 plus new ones." },
		],
		correct: "B",
		explanation:
			"Task 3.6: include prior findings on re-review and instruct to report only new/unaddressed. Without it, fixed bugs are re-flagged.",
		distractorRationales: {
			A: "Without prior findings, Claude can't know which were already flagged.",
			C: "Fresh context means fresh analysis, but bugs are still detectable.",
			D: "Claude flags what it sees, not 'doubles' anything.",
		},
		studyTags: ["prior-findings", "re-review", "Task-3.6"],
	},
	{
		id: "ci-q8",
		scenario: "ci-cd",
		domain: "D4",
		tasks: ["4.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A code review flags null-reference bugs with inconsistent severity: payment-flow null-ref → 'high'; logging-statement null-ref → 'high'; UI-component null-ref → 'low'. Most effective approach for consistent severity?",
		choices: [
			{ key: "A", text: "Add explicit instructions: 'High severity if in critical paths, low if non-critical.'" },
			{ key: "B", text: "Include 2-4 worked few-shot examples showing: critical-path null-ref → HIGH with reasoning; non-critical → MEDIUM with reasoning; defensive code → DO NOT FLAG." },
			{ key: "C", text: "Ask Claude to report confidence and filter low-confidence findings." },
			{ key: "D", text: "Run the review 3 times and average severity scores." },
		],
		correct: "B",
		explanation:
			"Task 4.2: few-shot examples establish consistent decision boundaries with explicit reasoning per case.",
		distractorRationales: {
			A: "'Critical vs non-critical' is still vague without examples.",
			C: "Self-reported confidence is poorly calibrated.",
			D: "Averaging adds noise; doesn't establish criteria.",
		},
		studyTags: ["few-shot", "severity-consistency", "Task-4.2"],
	},
	{
		id: "ci-q9",
		scenario: "ci-cd",
		domain: "D3",
		tasks: ["3.6"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Test generation: 'Generate Jest tests for src/auth.ts.' 60% of generated tests duplicate scenarios in __tests__/auth.test.ts. Why and how to fix?",
		choices: [
			{ key: "A", text: "Claude has no way to know what tests already exist; duplication is inevitable." },
			{ key: "B", text: "Include existing test files as context so Claude knows what's already covered. Instruct: 'Focus on gaps: new functions, edge cases not yet covered.'" },
			{ key: "C", text: "The codebase is over-tested; remove 60% of old tests." },
			{ key: "D", text: "Use a larger model (Opus) which has better knowledge of existing code." },
		],
		correct: "B",
		explanation:
			"Task 3.6: provide existing test files in test-gen context to avoid duplicates.",
		distractorRationales: {
			A: "Claude can see existing tests if included in context.",
			C: "Over-testing isn't the issue; missing new coverage is.",
			D: "Model size doesn't solve lack of context.",
		},
		studyTags: ["test-generation", "existing-tests", "Task-3.6"],
	},
	{
		id: "ci-q10",
		scenario: "ci-cd",
		domain: "D4",
		tasks: ["4.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Code review flags many 'unhandled promise rejection' issues. Team wants to understand how many are real bugs vs false positives. How to systematically analyze?",
		choices: [
			{ key: "A", text: "Track confidence scores for each finding." },
			{ key: "B", text: "Run the review multiple times and compare consensus." },
			{ key: "C", text: "Include a detected_pattern field in findings (e.g., detected_pattern: 'unhandled_promise_in_event_listener'). After 100 reviews, query: 'Of all findings with this pattern, what percent were FP?' Refine or disable the pattern." },
			{ key: "D", text: "Manually review findings and update criteria via anecdotal feedback." },
		],
		correct: "C",
		explanation:
			"Task 4.4: detected_pattern field enables quantitative FP analysis and iterative prompt improvement.",
		distractorRationales: {
			A: "Confidence scores are poorly calibrated.",
			B: "Consensus suppresses real bugs missed in some runs.",
			D: "Anecdotal feedback is unreliable.",
		},
		studyTags: ["detected_pattern", "FP-analysis", "Task-4.4"],
	},
	// Gotcha variant
	{
		id: "ci-q11",
		scenario: "ci-cd",
		domain: "D4",
		tasks: ["4.5"],
		mode: "gotcha",
		difficulty: "medium",
		stem: "An engineer wants to use the Message Batches API for a pre-merge PR review check that must complete before merge. They propose batching a job and falling back to sync if batch hasn't returned in 10 minutes. Why is this wrong?",
		choices: [
			{ key: "A", text: "The Batch API has no latency SLA — there is no guaranteed return time, including 10 minutes. Pre-merge checks must use sync from the start; the timeout-fallback adds complexity without solving the SLA gap." },
			{ key: "B", text: "Batch API requires a custom_id; without ordering, results can't be matched to inputs." },
			{ key: "C", text: "Pre-merge PR reviews aren't allowed to use batch by Anthropic terms of service." },
			{ key: "D", text: "Batch API doesn't support tool_use, which PR reviews require." },
		],
		correct: "A",
		explanation:
			"Task 4.5: Batch has no SLA. Decide upfront: blocking → sync; non-blocking → batch. Don't mix.",
		distractorRationales: {
			B: "custom_id is for correlation, not ordering. This isn't the why.",
			C: "Not a TOS issue; it's an architectural fit issue.",
			D: "Batch doesn't support multi-turn tool calling within a single request, but single-turn tool use works.",
		},
		studyTags: ["batch-no-sla", "no-fallback", "Task-4.5"],
	},
];
