import type { CertQuestion } from "./cert-types";

// Scenario 2: Code Generation with Claude Code
// Sourced from scenario-2-claude-code.md practice questions.
export const CODE_GENERATION_QUESTIONS: CertQuestion[] = [
	{
		id: "cg-q1",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.1"],
		mode: "canonical",
		difficulty: "easy",
		stem: "A new teammate Alice ran /init and CLAUDE.md was created, but Claude doesn't follow the team's API conventions (use server actions, not API routes). Where should you check first?",
		choices: [
			{ key: "A", text: "Alice's ~/.claude/CLAUDE.md — her personal overrides might be interfering." },
			{ key: "B", text: "The project .claude/CLAUDE.md — team-wide standards should be here." },
			{ key: "C", text: ".claude/rules/api-conventions.md — path-specific rules for all files." },
			{ key: "D", text: "Create a new skill to teach the convention on-demand." },
		],
		correct: "B",
		explanation:
			"Team standards must live in the project-level .claude/CLAUDE.md (VCS-checked). User-level CLAUDE.md is personal and not shared. The rule is missing because it was never added to the project file.",
		distractorRationales: {
			A: "User-level CLAUDE.md is for personal preferences. Alice's would be empty for team standards.",
			C: ".claude/rules/ uses glob patterns for conditional rules. Universal API conventions belong in CLAUDE.md.",
			D: "Skills are on-demand, not always-loaded standards.",
		},
		studyTags: ["CLAUDE.md-hierarchy", "project-vs-user", "Task-3.1"],
	},
	{
		id: "cg-q2",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.2"],
		mode: "canonical",
		difficulty: "easy",
		stem: "Your team has a /pre-commit command that runs linting, type-checking, and formatting. You want all teammates to use it. Where should you create it?",
		choices: [
			{ key: "A", text: ".claude/commands/pre-commit.md in the project repository." },
			{ key: "B", text: "~/.claude/commands/pre-commit.md in your home directory." },
			{ key: "C", text: "In the project CLAUDE.md under a 'Commands' section." },
			{ key: "D", text: "As a skill in .claude/skills/pre-commit/SKILL.md." },
		],
		correct: "A",
		explanation:
			"Slash commands shared with the team go in .claude/commands/ inside the project (VCS-versioned). The filename becomes the command name.",
		distractorRationales: {
			B: "Personal commands. Teammates won't have it.",
			C: "CLAUDE.md is for instructions/context, not executable command definitions.",
			D: "Skills are for on-demand task expertise, not team-wide command-line shortcuts.",
		},
		studyTags: ["slash-commands", "project-commands", "Task-3.2"],
	},
	{
		id: "cg-q3",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Your codebase has test files in five locations: tests/, src/__tests__/, app/__tests__/, packages/utils/__tests__/, and e2e/. You need to enforce consistent test conventions (Vitest, describe blocks, MSW). Best approach?",
		choices: [
			{ key: "A", text: "Create .claude/rules/testing.md with glob patterns ['**/__tests__/**', '**/*.test.ts']." },
			{ key: "B", text: "Create five separate CLAUDE.md files in each directory." },
			{ key: "C", text: "Add all testing rules to the main project CLAUDE.md." },
			{ key: "D", text: "Create a skill that developers invoke when writing tests." },
		],
		correct: "A",
		explanation:
			"Glob-based path rules in .claude/rules/ work across the entire codebase without requiring directory structure alignment. DRY and deterministic.",
		distractorRationales: {
			B: "Requires mirroring directory structure. Five duplicate files. Not DRY.",
			C: "Pollutes CLAUDE.md with rules that don't apply everywhere.",
			D: "Skills are on-demand and developers might forget to invoke them.",
		},
		studyTags: ["glob-rules", "path-conditional", "Task-3.3"],
	},
	{
		id: "cg-q4",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You want to create a skill that maps the entire monorepo architecture (50+ file reads and grep calls). Should the skill use context: fork?",
		choices: [
			{ key: "A", text: "Yes. The exploration work stays in a sub-agent; only the summary returns to main context." },
			{ key: "B", text: "No. The skill should run in the main context so you can see all its reasoning." },
			{ key: "C", text: "Only if you plan to use the skill more than twice." },
			{ key: "D", text: "Only if the skill takes longer than 5 minutes to run." },
		],
		correct: "A",
		explanation:
			"Verbose exploratory work clutters main context. context: fork isolates tool calls and reasoning in a sub-agent, returning only the summary.",
		distractorRationales: {
			B: "Seeing all reasoning is not important; the answer (architecture map) is what you need.",
			C: "Frequency doesn't determine context: fork. The benefit is context pollution avoidance.",
			D: "Duration doesn't determine context: fork either.",
		},
		studyTags: ["context-fork", "skills", "Task-3.2"],
	},
	{
		id: "cg-q5",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You need to refactor a legacy monolithic API into microservices. This affects 45 files, 3 new services, database layer changes, and API contract changes. Multiple architectural approaches exist. Should you use plan mode?",
		choices: [
			{ key: "A", text: "Yes. Plan mode lets Claude explore, understand dependencies, design an approach, and get your approval before executing." },
			{ key: "B", text: "No. Direct execution is faster; start coding and iterate." },
			{ key: "C", text: "Use plan mode only if the codebase is larger than 50 files." },
			{ key: "D", text: "Use direct execution; plan mode is overkill for refactoring." },
		],
		correct: "A",
		explanation:
			"Plan mode is designed for multi-file architectural decisions with multiple valid approaches. Direct execution risks discovering mid-way that the approach is wrong.",
		distractorRationales: {
			B: "Direct execution on large architectural changes is risky; you'll iterate multiple times.",
			C: "File count is not the criterion. The decision factor is scope, architectural nature, and approach ambiguity.",
			D: "Plan mode is exactly for large refactorings.",
		},
		studyTags: ["plan-mode", "architectural-decisions", "Task-3.4"],
	},
	{
		id: "cg-q6",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You're asking Claude to convert legacy user objects to a new schema. You explained requirements in prose, but output doesn't match expectations on edge cases. Fastest fix?",
		choices: [
			{ key: "A", text: "Describe edge cases in more prose: 'Handle null addresses, treat empty strings as missing data...'" },
			{ key: "B", text: "Provide 3-4 concrete input/output examples showing exactly how edge cases should be handled." },
			{ key: "C", text: "Ask Claude to review its own output for correctness." },
			{ key: "D", text: "Provide a test suite with failing tests for edge cases." },
		],
		correct: "B",
		explanation:
			"Concrete examples eliminate ambiguity faster than prose for transformation tasks. Claude aligns behavior to match the examples.",
		distractorRationales: {
			A: "More prose doesn't fix the ambiguity problem.",
			C: "Self-review is ineffective due to retained generation reasoning.",
			D: "Tests are valid (test-driven) but examples are faster for transformation rules.",
		},
		studyTags: ["concrete-examples", "iterative-refinement", "Task-3.5"],
	},
	{
		id: "cg-q7",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You have two bugs: (1) cache isn't invalidated after updates causing stale reads, and (2) concurrent updates step on each other (race condition). Best approach?",
		choices: [
			{ key: "A", text: "One message: 'Fix both bugs. They interact — cache invalidation must be atomic with the update to prevent races.'" },
			{ key: "B", text: "Two sequential messages: First fix the cache bug, then fix the race condition." },
			{ key: "C", text: "Three messages: First understand the race condition, then the cache, then fix both." },
			{ key: "D", text: "Use plan mode to design both fixes simultaneously." },
		],
		correct: "A",
		explanation:
			"The bugs interact. One message ensures Claude understands the interaction and fixes both atomically. Sequential messages risk one fix re-introducing the other.",
		distractorRationales: {
			B: "Ignores the interaction. Second fix might break the first.",
			C: "Over-complicated. No need to understand separately.",
			D: "Plan mode for individual bugs isn't necessary.",
		},
		studyTags: ["interacting-problems", "single-message", "Task-3.5"],
	},
	{
		id: "cg-q8",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You want Claude to implement a state machine for order processing (draft → confirmed → shipped → delivered, with rollback). Best approach?",
		choices: [
			{ key: "A", text: "Describe the state machine in prose and iterate on Claude's output." },
			{ key: "B", text: "Provide a test suite with cases for valid transitions, invalid transitions, and rollbacks. Have Claude implement to pass tests." },
			{ key: "C", text: "Ask Claude to design the state machine first, then implement it." },
			{ key: "D", text: "Use a skill to define state machine conventions and invoke it." },
		],
		correct: "B",
		explanation:
			"Test-driven iteration is most effective for behavior correctness. Tests define ground truth; failures are concrete; fixes are targeted.",
		distractorRationales: {
			A: "Prose iteration is slow and error-prone.",
			C: "Waterfall approach; test-driven tightens the loop.",
			D: "Skills teach conventions, not state machine logic.",
		},
		studyTags: ["test-driven", "iterative-refinement", "Task-3.5"],
	},
	{
		id: "cg-q9",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.6", "4.6"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You just finished implementing an authentication module. Before committing, you ask Claude in the same session, 'Review the code I just wrote for security issues.' Claude reviews and approves. Is this effective?",
		choices: [
			{ key: "A", text: "Yes. Claude just wrote the code, so it understands the intent and context." },
			{ key: "B", text: "No. The same session that generated the code is less effective at reviewing it. Use a subagent reviewer for independent eyes." },
			{ key: "C", text: "Neutral. It depends on the complexity of the code." },
			{ key: "D", text: "Yes, if you prepend the review request with 'Pretend you didn't write this code.'" },
		],
		correct: "B",
		explanation:
			"Same-session self-review is unreliable. The model retains generation reasoning ('I implemented this correctly'). An independent subagent has fresh context.",
		distractorRationales: {
			A: "Understanding intent is a disadvantage; bias toward generated code leads to missed bugs.",
			C: "Independent review is consistently better — not contingent on complexity.",
			D: "Prepending a statement doesn't override model behavior.",
		},
		studyTags: ["session-isolation", "independent-review", "Task-3.6", "Task-4.6"],
	},
	{
		id: "cg-q10",
		scenario: "code-generation",
		domain: "D5",
		tasks: ["5.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You're exploring a large monorepo. After Grep finding 50 matches, Reading 20 key files, and 15 more queries, your context is 60% full and you haven't started implementation. Best next step?",
		choices: [
			{ key: "A", text: "Continue exploring; you'll need this context for implementation." },
			{ key: "B", text: "Run /compact to summarize exploration findings and free context." },
			{ key: "C", text: "Run /clear to start fresh." },
			{ key: "D", text: "Spawn a subagent to continue exploration in isolated context." },
		],
		correct: "B",
		explanation:
			"/compact summarizes exploration, keeps key findings, frees context for implementation. Preserves discoveries while freeing space.",
		distractorRationales: {
			A: "60% full risks inconsistency and lost-in-the-middle effects.",
			C: "/clear discards all findings. You'd re-explore.",
			D: "Subagents are better for delegating future work, not recovering from current bloat.",
		},
		studyTags: ["compact", "context-management", "Task-5.4"],
	},
	{
		id: "cg-q11",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Your project CLAUDE.md has grown to 250 lines covering API conventions, database rules, testing, deployment, and code style. It's hard to maintain. Best refactor?",
		choices: [
			{ key: "A", text: "Split into separate files in .claude/rules/ with glob patterns and use @import in the main CLAUDE.md." },
			{ key: "B", text: "Create separate CLAUDE.md files in each subdirectory." },
			{ key: "C", text: "Create skills for each topic." },
			{ key: "D", text: "Leave it as is; 250 lines is manageable." },
		],
		correct: "A",
		explanation:
			"@import allows modularizing CLAUDE.md while keeping it VCS-controlled. Easier to review, merge, and maintain.",
		distractorRationales: {
			B: "Subdirectory CLAUDE.md files require directory structure alignment. Not ideal for scattered conventions.",
			C: "Skills are for on-demand tasks, not universal standards.",
			D: "250 lines is already hard to review and maintain.",
		},
		studyTags: ["@import", "modularity", "Task-3.1"],
	},
	{
		id: "cg-q12",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.5", "5.4"],
		mode: "canonical",
		difficulty: "hard",
		stem: "You spent a session exploring a codebase and identified 12 API endpoints, 3 middleware, current auth flow, and missing tests. Next day you need to implement a new auth feature. Should you use claude --resume or start a new session?",
		choices: [
			{ key: "A", text: "Use --resume. Your prior exploration is still relevant." },
			{ key: "B", text: "Start a new session. Files may have changed; include a structured summary of your prior findings." },
			{ key: "C", text: "Use --resume but ask Claude to re-verify the exploration findings." },
			{ key: "D", text: "Start fresh with no context; re-explore to be safe." },
		],
		correct: "B",
		explanation:
			"Files might have changed overnight. Prior tool results could be stale. New session with a structured summary is safer than resuming with stale information.",
		distractorRationales: {
			A: "Without verification, stale findings could mislead implementation.",
			C: "Resume + verify is extra work; new + summary is cleaner.",
			D: "Re-exploring wastes time when you have documented findings.",
		},
		studyTags: ["session-resume", "stale-tool-results", "Task-5.4"],
	},
	{
		id: "cg-q13",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.2"],
		mode: "canonical",
		difficulty: "easy",
		stem: "You create a code-review subagent skill. What should allowed-tools be?",
		choices: [
			{ key: "A", text: "All tools: Read, Write, Edit, Grep, Glob, Bash." },
			{ key: "B", text: "Read, Grep, Glob (read-only)." },
			{ key: "C", text: "Only Read." },
			{ key: "D", text: "No restriction; let the agent choose." },
		],
		correct: "B",
		explanation:
			"A reviewer should not edit files. Restrict to read-only. Grep and Glob are needed to explore the code and understand context.",
		distractorRationales: {
			A: "Granting write access to a reviewer creates risk.",
			C: "Too restrictive. Grep and Glob needed for context.",
			D: "Unrestricted access is a security risk.",
		},
		studyTags: ["allowed-tools", "skill-permissions", "Task-3.2"],
	},
	{
		id: "cg-q14",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.6"],
		mode: "canonical",
		difficulty: "easy",
		stem: "Your CI/CD pipeline uses Claude Code to auto-generate PR descriptions, run with the claude command non-interactively. It hangs. What's the fix?",
		choices: [
			{ key: "A", text: "Use -p / --print flag for non-interactive mode, preventing prompts and hangs." },
			{ key: "B", text: "Set the CLAUDE_CI_MODE=true environment variable." },
			{ key: "C", text: "Redirect stdin to /dev/null." },
			{ key: "D", text: "Use the -y flag to auto-approve all prompts." },
		],
		correct: "A",
		explanation:
			"The -p (print) flag tells Claude Code to run non-interactively without prompts, preventing hangs in CI/CD.",
		distractorRationales: {
			B: "No such environment variable exists.",
			C: "Doesn't prevent interactive prompts.",
			D: "No -y flag exists.",
		},
		studyTags: ["-p-flag", "non-interactive", "Task-3.6"],
	},
	{
		id: "cg-q15",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Your codebase has deployment scripts in scripts/deploy/, ci/deploy/, and helm/. Different languages but all follow 'always log the deployment step.' Where should you put this rule?",
		choices: [
			{ key: "A", text: "In three separate deploy/CLAUDE.md files (one per directory)." },
			{ key: "B", text: "In .claude/rules/deployment.md with paths: ['scripts/deploy/**', 'ci/deploy/**', 'helm/**']." },
			{ key: "C", text: "In the main project CLAUDE.md." },
			{ key: "D", text: "As a skill that developers invoke before editing deployment scripts." },
		],
		correct: "B",
		explanation:
			"Glob paths in .claude/rules/ efficiently target scattered files without redundant CLAUDE.md files. Path-scoped but not directory-scoped.",
		distractorRationales: {
			A: "Three duplicate files. Not DRY.",
			C: "Pollutes main CLAUDE.md with rules that only apply to deployment files.",
			D: "Skills are on-demand; should always apply when editing deployment scripts.",
		},
		studyTags: ["glob-rules", "scattered-conventions", "Task-3.3"],
	},
	{
		id: "cg-q16",
		scenario: "code-generation",
		domain: "D5",
		tasks: ["5.1"],
		mode: "canonical",
		difficulty: "hard",
		stem: "You've spent 200 messages refactoring auth across 15 files. You need Claude to remember refactoring decisions (token expiry: 1 hour, session timeout: 30 min, reset window: 24 hours). Context is 80% full. How do you preserve these critical facts for the next phase?",
		choices: [
			{ key: "A", text: "Rely on earlier messages in conversation history; Claude will recall when needed." },
			{ key: "B", text: "Extract transaction facts (token expiry: 1 hour, session timeout: 30 min, reset window: 24 hours) into a persistent case facts block in your next prompt, outside summarized history." },
			{ key: "C", text: "Use /compact to preserve the exact details from prior messages." },
			{ key: "D", text: "Start a new session with --resume to maintain full conversation history." },
		],
		correct: "B",
		explanation:
			"Task 5.1: a persistent 'case facts block' with key transaction data survives context boundaries and is reliably recalled. Progressive summarization loses specific numbers.",
		distractorRationales: {
			A: "Lost-in-the-middle effect means buried facts get lost.",
			C: "/compact summarizes but vague paraphrasing loses precision (e.g., 'around one hour' vs '3600 seconds').",
			D: "Resuming preserves history but doesn't extract critical facts into a dedicated block.",
		},
		studyTags: ["case-facts-block", "long-conversation", "Task-5.1"],
	},
	// Trick variant
	{
		id: "cg-q17",
		scenario: "code-generation",
		domain: "D3",
		tasks: ["3.4"],
		mode: "trick",
		difficulty: "medium",
		stem: "An engineer provides this stack trace: 'Error at line 127 in utils/validate.ts: TypeError: expected string, got undefined'. The fix is a single null check. The engineer has confirmed the file path and behavior. Should Claude Code use plan mode?",
		choices: [
			{ key: "A", text: "Plan mode, to explore the codebase first." },
			{ key: "B", text: "Direct execution; the scope is clear, the file is identified, and the fix is straightforward." },
			{ key: "C", text: "Plan mode first, then direct execution." },
			{ key: "D", text: "Use an Explore subagent to determine the best approach." },
		],
		correct: "B",
		explanation:
			"Direct execution for single-file, clear-scope, low-risk fixes. The stem already supplies file, line, and behavior — there's nothing to explore.",
		distractorRationales: {
			A: "Overkill for a one-line fix with clear scope.",
			C: "Adds unnecessary overhead; direct execution suffices.",
			D: "Subagent exploration is unnecessary when scope is already known.",
		},
		studyTags: ["direct-execution", "plan-vs-direct", "Task-3.4"],
	},
];
