import type { CertQuestion } from "./cert-types";

// Scenario 1: Customer Support Resolution Agent
// Sourced from scenario-1-customer-support.md practice questions.
export const CUSTOMER_SUPPORT_QUESTIONS: CertQuestion[] = [
	{
		id: "cs-q1",
		scenario: "customer-support",
		domain: "D1",
		tasks: ["1.4", "1.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A customer calls in with 'I want a refund for order #12345.' The agent successfully looks up the order but skips get_customer verification ~12% of the time, directly calling process_refund with just the order number. This results in refunds being issued to the wrong account ~7% of the time. The agent's FCR is being harmed. Which of the following is the most effective fix?",
		choices: [
			{ key: "A", text: "Add a system prompt instruction: 'Always verify the customer's identity via get_customer before processing any refund.'" },
			{ key: "B", text: "Implement a programmatic prerequisite gate that prevents process_refund from executing unless get_customer has returned a verified customer ID in the current session." },
			{ key: "C", text: "Add three few-shot examples to the system prompt showing scenarios where get_customer is called before process_refund." },
			{ key: "D", text: "Build a routing classifier that detects refund requests and forces get_customer to be called first." },
		],
		correct: "B",
		explanation:
			"Task 1.4 requires programmatic enforcement for deterministic compliance when errors have financial consequences. Hooks/gates give guarantees; prompts give probabilities (the 12% skip rate is exactly that probabilistic failure).",
		distractorRationales: {
			A: "Prompt-based instruction; agent will still skip ~10% of the time as it already does.",
			C: "Few-shot helps with ambiguous cases, not deterministic sequencing. The agent already knows the concept; the problem is execution failure.",
			D: "Over-engineered. A simple prerequisite exception is simpler and more reliable than a routing classifier.",
		},
		studyTags: ["prerequisite-gate", "hooks", "deterministic-enforcement", "Task-1.4", "Task-1.5"],
	},
	{
		id: "cs-q2",
		scenario: "customer-support",
		domain: "D2",
		tasks: ["2.1"],
		mode: "canonical",
		difficulty: "easy",
		stem: "An agent has two tools: get_customer (description: 'Get customer info') and lookup_order (description: 'Look up order info'). When a customer says 'Can you check on my account?', the agent picks lookup_order ~30% of the time instead of get_customer. What is the most effective first step to improve tool selection reliability?",
		choices: [
			{ key: "A", text: "Add 4 few-shot examples to the system prompt showing when to use each tool." },
			{ key: "B", text: "Expand each tool's description with input formats, example queries, when-to-use vs when-not-to-use guidance, and boundary cases." },
			{ key: "C", text: "Build a pre-processing classifier that routes customer requests to the correct tool before the agent sees them." },
			{ key: "D", text: "Consolidate get_customer and lookup_order into a single query_backend tool with mode parameters." },
		],
		correct: "B",
		explanation:
			"Task 2.1 names tool descriptions as the primary signal LLMs use for tool selection. Fix descriptions BEFORE adding few-shot or building routing layers.",
		distractorRationales: {
			A: "Few-shot is a second-order fix; descriptions come first.",
			C: "Over-engineered. Better descriptions solve this without an additional component.",
			D: "Consolidation loses functional clarity and makes both use cases less reliable.",
		},
		studyTags: ["tool-descriptions", "tool-selection", "Task-2.1"],
	},
	{
		id: "cs-q3",
		scenario: "customer-support",
		domain: "D5",
		tasks: ["5.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "An agent operating a support channel is achieving 55% FCR. It escalates straightforward billing questions while attempting complex policy exception requests (which should be escalated). Justifications vary: sometimes 'I'm not confident,' sometimes 'The customer sounds frustrated.' To improve calibration toward 80%+ FCR, which approach is most effective?",
		choices: [
			{ key: "A", text: "Define explicit escalation criteria in the system prompt (e.g., 'escalate if: customer requests human, OR policy does not explicitly cover the use case, OR refund > threshold') and provide 2-3 few-shot examples of boundary cases showing the reasoning." },
			{ key: "B", text: "Add sentiment analysis to detect frustration and escalate high-frustration cases automatically." },
			{ key: "C", text: "Train a separate ML classifier on historical escalation decisions to predict when to escalate." },
			{ key: "D", text: "Add a self-confidence threshold: only escalate if the agent's self-reported confidence drops below 60%." },
		],
		correct: "A",
		explanation:
			"Task 5.2 names sentiment-based escalation and self-reported confidence as anti-patterns. Explicit criteria + few-shot are tunable and interpretable.",
		distractorRationales: {
			B: "Sentiment doesn't correlate with escalation need. A calm customer with a policy gap should still be escalated.",
			C: "ML is over-engineered when explicit rules + few-shot work and remain interpretable.",
			D: "LLM self-reported confidence is poorly calibrated; the agent is already incorrectly confident on hard cases.",
		},
		studyTags: ["explicit-criteria", "few-shot", "no-sentiment", "no-self-confidence", "Task-5.2"],
	},
	{
		id: "cs-q4",
		scenario: "customer-support",
		domain: "D2",
		tasks: ["2.2", "5.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A tool call to lookup_order times out. The agent receives: { 'error': 'Operation failed' }. The agent doesn't know whether to retry, ask the customer for clarification, escalate, or try an alternative. Which response structure best enables intelligent recovery?",
		choices: [
			{ key: "A", text: "{ 'isError': true, 'errorCategory': 'transient', 'isRetryable': true, 'description': 'Backend service timeout after 30s. Retry in 5 seconds.' }" },
			{ key: "B", text: "{ 'error': 'Service unavailable. Please try again later.' }" },
			{ key: "C", text: "{ 'status': 'failed', 'reason': 'timeout', 'message': 'The lookup operation could not complete in time.' }" },
			{ key: "D", text: "{ 'isError': true, 'errorCategory': 'transient', 'description': 'Backend service temporarily unavailable.' }" },
		],
		correct: "A",
		explanation:
			"Task 2.2 specifies structured errors with errorCategory + isRetryable + description. With these, the agent can decide: retry, ask user, or escalate.",
		distractorRationales: {
			B: "Generic message, no categorization, no recovery decision possible.",
			C: "Has 'reason' but lacks errorCategory + isRetryable flags.",
			D: "Missing isRetryable; the agent doesn't know whether retrying will succeed.",
		},
		studyTags: ["structured-errors", "errorCategory", "isRetryable", "Task-2.2", "Task-5.3"],
	},
	{
		id: "cs-q5",
		scenario: "customer-support",
		domain: "D1",
		tasks: ["1.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A support agent gets data from heterogeneous backends: System A returns customer_id as integer and dates as Unix timestamps; System B returns status as numeric code (2 = 'shipped') and dates as ISO strings. The agent occasionally treats status codes as priorities. How should this be addressed?",
		choices: [
			{ key: "A", text: "Add instructions to the system prompt: 'Normalize all dates to ISO 8601 format and all status codes to English labels.'" },
			{ key: "B", text: "Implement a PostToolUse hook that normalizes tool results before the agent sees them (Unix → ISO 8601, numeric codes → enum labels, integer IDs → string IDs)." },
			{ key: "C", text: "Have the agent explicitly request formatted data from each tool by specifying output format in tool parameters." },
			{ key: "D", text: "Build a post-processing layer that the agent calls after each tool to normalize results." },
		],
		correct: "B",
		explanation:
			"Task 1.5: PostToolUse hooks normalize heterogeneous formats deterministically. Hooks run every time; prompt-based normalization is probabilistic.",
		distractorRationales: {
			A: "Prompt-based normalization; agent still sees inconsistent data first.",
			C: "Doesn't solve the problem if backends return inconsistent formats.",
			D: "Requires the agent to remember to call the layer; hooks are automatic.",
		},
		studyTags: ["PostToolUse", "hooks", "normalization", "Task-1.5"],
	},
	{
		id: "cs-q6",
		scenario: "customer-support",
		domain: "D1",
		tasks: ["1.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A support agent determines a refund of $750 exceeds the policy limit ($500) and escalates to a human. What should the escalation handoff include so the human can decide without making the customer re-verify?",
		choices: [
			{ key: "A", text: "'Escalate to human for review. Reason: refund amount exceeds policy.'" },
			{ key: "B", text: "A JSON object with customer_id, customer_email, issue, requested_amount, policy_limit, order_id, items, attempted_resolution, and recommendation." },
			{ key: "C", text: "A link to the conversation history." },
			{ key: "D", text: "The conversation transcript copied to the escalation ticket." },
		],
		correct: "B",
		explanation:
			"Task 1.4 requires a structured handoff (customer ID, root cause, recommended action, attempted resolution). Humans don't have transcript access on different shifts/queues.",
		distractorRationales: {
			A: "Prose summary with no customer ID or order details; human must re-verify.",
			C: "Link assumes the human has chat access; not always available.",
			D: "Verbose, doesn't highlight key facts (policy limit, recommended action).",
		},
		studyTags: ["structured-handoff", "escalation", "Task-1.4"],
	},
	{
		id: "cs-q7",
		scenario: "customer-support",
		domain: "D5",
		tasks: ["5.1"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A multi-turn support conversation accumulates over 4 turns. Aggressive summarization compresses 'refund of $49.99 for order #123 from 2026-04-15' into 'refund on April order.' How should this precision loss be prevented?",
		choices: [
			{ key: "A", text: "Disable summarization; keep the full conversation history." },
			{ key: "B", text: "Use prompting: 'Remember the order ID is 123, the date is 2026-04-15, and the refund amount is $49.99.'" },
			{ key: "C", text: "Maintain a persistent case facts block outside the conversation history, refreshed after each turn with discovered facts (customer ID, order ID, dates, amounts, status). Include this block in the system prompt for each API call." },
			{ key: "D", text: "Store order metadata in a database and query it each turn instead of relying on conversation history." },
		],
		correct: "C",
		explanation:
			"Task 5.1: a case facts block is a structured persistent layer outside summarized history. It's prepended to the system prompt for each API call and refreshed each turn.",
		distractorRationales: {
			A: "Unbounded context growth; impractical for long conversations.",
			B: "Prompting doesn't prevent summarization loss; the agent still sees the same compressed history.",
			D: "Adds latency and complexity; case facts block is sufficient.",
		},
		studyTags: ["case-facts-block", "context-preservation", "Task-5.1"],
	},
	{
		id: "cs-q8",
		scenario: "customer-support",
		domain: "D1",
		tasks: ["1.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A customer says: 'I was charged twice for order #A12, one item arrived damaged, and I need to update my billing address.' Trying to reason about all three at once produces tangled output. How should the agent decompose this?",
		choices: [
			{ key: "A", text: "Attempt all three in parallel within a single agent call to minimize latency." },
			{ key: "B", text: "Decompose into distinct concerns: (1) duplicate charge → lookup_order + process_refund (escalate if > $500), (2) damaged item → lookup_order + initiate_replacement (escalate if discontinued), (3) billing address → update_customer_info (escalate if verification fails). Reason over each separately." },
			{ key: "C", text: "Ask the customer which issue is most urgent and address only that one." },
			{ key: "D", text: "Combine all concerns into a single handle_complex_case tool call with all parameters." },
		],
		correct: "B",
		explanation:
			"Task 1.4: decompose multi-concern customer requests into distinct (concern, action, escalation_trigger) items. Each has its own investigation path.",
		distractorRationales: {
			A: "Parallel processing doesn't prevent context tangling in reasoning.",
			C: "Avoids the customer's actual request.",
			D: "Consolidation hides the distinct logic and makes escalation triggers unclear.",
		},
		studyTags: ["decomposition", "multi-concern", "Task-1.4"],
	},
	{
		id: "cs-q9",
		scenario: "customer-support",
		domain: "D2",
		tasks: ["2.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A synthesis agent integrates findings from sub-agents. It has access to: web_search, get_customer, lookup_order, verify_fact, initiate_replacement. It speculatively calls get_customer and lookup_order on entities mentioned in sub-agent reports, increasing latency without improving report quality. Best fix?",
		choices: [
			{ key: "A", text: "Add a system prompt instruction: 'Do not call get_customer or lookup_order unless explicitly required.'" },
			{ key: "B", text: "Restrict the synthesis agent's tool set to only verify_fact and web_search (tools aligned with its synthesis role)." },
			{ key: "C", text: "Add a cost warning to the tool descriptions." },
			{ key: "D", text: "Train the synthesis agent on a corpus of good vs bad synthesis reports." },
		],
		correct: "B",
		explanation:
			"Task 2.3: scoped access — each agent gets only the tools needed for its role. Removing the tools makes misuse impossible (deterministic vs prompt-probabilistic).",
		distractorRationales: {
			A: "Prompt-based guidance; agent will still misuse some percentage of the time.",
			C: "Cost warnings don't prevent misuse; agent optimizes for output quality.",
			D: "Doesn't address the root cause (unnecessary tool access).",
		},
		studyTags: ["scoped-tools", "tool-distribution", "Task-2.3"],
	},
	{
		id: "cs-q10",
		scenario: "customer-support",
		domain: "D5",
		tasks: ["5.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Customer purchased a laptop on 2026-01-10 and asks for a competitor price match on 2026-04-26 (107 days later). Policy: 'We match competitor prices on identical in-stock items within 30 days of purchase.' What should the agent do?",
		choices: [
			{ key: "A", text: "Attempt to resolve by explaining the policy and offering a smaller goodwill discount." },
			{ key: "B", text: "Escalate immediately to a human with the policy gap noted: 'Customer requests price match 107 days after purchase. Policy limit is 30 days. Manager exception consideration required.'" },
			{ key: "C", text: "Escalate only if the customer expresses frustration after hearing the policy." },
			{ key: "D", text: "Apply sentiment analysis; if calm, attempt resolution; if frustrated, escalate." },
		],
		correct: "B",
		explanation:
			"Task 5.2: escalate when policy is silent or a specific request is outside policy scope. The boundary is exceeded regardless of tone.",
		distractorRationales: {
			A: "Policy is clear; this isn't a gray area where negotiation makes sense.",
			C: "Escalation shouldn't depend on tone; the policy boundary is already exceeded.",
			D: "Sentiment doesn't correlate with whether policy applies.",
		},
		studyTags: ["policy-gap", "explicit-escalation", "no-sentiment", "Task-5.2"],
	},
	// Gotcha-flavored variants from scenario gotcha list.
	{
		id: "cs-q11",
		scenario: "customer-support",
		domain: "D5",
		tasks: ["5.2"],
		mode: "gotcha",
		difficulty: "medium",
		stem: "A customer support agent currently escalates only when its self-reported confidence drops below 60%. Engineers notice it confidently misroutes 'I want to cancel and get a full refund' (a clear policy exception) while escalating routine status-check questions. Why is the self-reported confidence threshold a poor signal?",
		choices: [
			{ key: "A", text: "LLM self-reported confidence is poorly calibrated — agents are often most confident on hard cases and uncertain on straightforward ones. Escalation should be driven by explicit policy criteria." },
			{ key: "B", text: "The threshold is set too high; lowering it to 40% will catch the misrouted cases." },
			{ key: "C", text: "Confidence is unreliable only when the model is small; switch to a larger Claude model." },
			{ key: "D", text: "The agent should compute its confidence using log-probabilities instead of asking itself." },
		],
		correct: "A",
		explanation:
			"Task 5.2 explicitly lists self-reported confidence as an anti-pattern for escalation. Explicit policy criteria are the canonical fix.",
		distractorRationales: {
			B: "Tuning the threshold doesn't fix a fundamentally miscalibrated signal.",
			C: "Model size doesn't solve calibration of self-reported confidence.",
			D: "Log-probabilities aren't reliably exposed and still don't correlate with policy fit.",
		},
		studyTags: ["no-self-confidence", "explicit-criteria", "Task-5.2"],
	},
	{
		id: "cs-q12",
		scenario: "customer-support",
		domain: "D5",
		tasks: ["5.2"],
		mode: "trick",
		difficulty: "hard",
		stem: "A customer support agent's lookup_order returns three matches because the customer's name 'Alice Johnson' is common. Three orders share that name with different totals and dates. The system has structured handoff configured and explicit escalation criteria. What should the agent do?",
		choices: [
			{ key: "A", text: "Pick the order with the highest total — it's most likely the customer's main account." },
			{ key: "B", text: "Pick the most recent order — recency usually wins in customer intent." },
			{ key: "C", text: "Ask the customer for an additional identifier (e.g., 'Which of these three orders: #111, #222, or #333 from these dates?') with concrete distinguishing details." },
			{ key: "D", text: "Escalate to a human because the disambiguation indicates a system data quality issue." },
		],
		correct: "C",
		explanation:
			"Task 5.2: multi-customer matches require an explicit additional identifier request. Don't pick by heuristic. The structured handoff isn't relevant here — disambiguation is a self-serve action, not an escalation trigger.",
		distractorRationales: {
			A: "Heuristic selection guarantees wrong outcomes in edge cases.",
			B: "Same problem; recency is still a heuristic.",
			D: "Premature escalation; the customer can disambiguate immediately.",
		},
		studyTags: ["disambiguation", "multi-customer-match", "Task-5.2"],
	},
];
