import type { CertQuestion } from "./cert-types";

// Scenario 3: Multi-Agent Research System
export const MULTI_AGENT_QUESTIONS: CertQuestion[] = [
	{
		id: "ma-q1",
		scenario: "multi-agent-research",
		domain: "D1",
		tasks: ["1.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A coordinator researches 'modern business management techniques.' It decomposes into subagent queries: (1) 'lean methodology,' (2) 'agile frameworks.' Final report covers only agile and lean, missing management by objectives, total quality management, and other major methodologies. Which is the root cause?",
		choices: [
			{ key: "A", text: "Web-search-agent timed out on queries it didn't attempt." },
			{ key: "B", text: "Coordinator's task decomposition was too narrow for a broad topic." },
			{ key: "C", text: "Synthesis agent arbitrarily dropped findings on omitted methodologies." },
			{ key: "D", text: "Document-analysis-agent returned empty results for TQM." },
		],
		correct: "B",
		explanation:
			"The coordinator failed to decompose the broad topic comprehensively. Subagents worked correctly within scope; the scope itself was inadequate.",
		distractorRationales: {
			A: "Agent never ran = not the root cause; this is a decomposition failure.",
			C: "Synthesis received nothing to synthesize on omitted topics.",
			D: "Document agent wasn't asked to analyze TQM.",
		},
		studyTags: ["narrow-decomposition", "broad-topic", "Task-1.2"],
	},
	{
		id: "ma-q2",
		scenario: "multi-agent-research",
		domain: "D5",
		tasks: ["2.2", "5.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Web-search-agent times out searching for 'renewable energy statistics 2024.' It returns { 'status': 'error', 'message': 'search unavailable' }. Coordinator terminates the workflow. What's the better error response?",
		choices: [
			{ key: "A", text: "{ errorCategory: 'transient', isRetryable: true, attempted_query: '...', partial_results: [...], alternatives_tried: [...], description: 'Request timed out before completion' }" },
			{ key: "B", text: "{ status: 'error', message: 'search unavailable - please retry manually' }" },
			{ key: "C", text: "{ status: 'success', results: [], reason: 'no matches found' }" },
			{ key: "D", text: "Retry automatically 5 times with exponential backoff before reporting to coordinator." },
		],
		correct: "A",
		explanation:
			"Task 2.2: structured error context with errorCategory, isRetryable, attempted query, partial results, alternatives. Coordinator can then decide recovery strategy.",
		distractorRationales: {
			B: "Generic message; coordinator can't make informed decisions.",
			C: "Conflates empty result with timeout; prevents proper recovery.",
			D: "Local retry only helps for transient network hiccups; the structured response should still propagate.",
		},
		studyTags: ["structured-errors", "error-categories", "Task-2.2", "Task-5.3"],
	},
	{
		id: "ma-q3",
		scenario: "multi-agent-research",
		domain: "D2",
		tasks: ["2.3"],
		mode: "canonical",
		difficulty: "hard",
		stem: "Synthesis subagent synthesizes 100 findings across 8 sources. It emits a verify_claim call for each, routed back to coordinator which re-delegates to web-search-agent. Latency is 40% of total system time. Which improves latency most?",
		choices: [
			{ key: "A", text: "Give synthesis agent the full web-search toolkit so it verifies locally without coordinator round-trips." },
			{ key: "B", text: "Give synthesis agent a scoped verify_fact tool that accepts a claim + list of known sources, returns 'matches / contradicts / unclear.' For 85% of checks, synthesis completes locally; 15% edge cases still route to coordinator." },
			{ key: "C", text: "Batch all 100 verification requests into a single coordinator call." },
			{ key: "D", text: "Pre-cache all likely verification needs before synthesis starts." },
		],
		correct: "B",
		explanation:
			"Scoped cross-role tool solves 85% of verifications locally. Complex cases still route to coordinator, preserving separation of concerns.",
		distractorRationales: {
			A: "Full toolkit causes mission creep; synthesis drifts into research instead of integration.",
			C: "Batched verification creates blocking dependency; synthesis needs to verify mid-stream.",
			D: "Speculative caching fails — synthesis discovers unexpected verification needs as it writes.",
		},
		studyTags: ["scoped-cross-role-tool", "verify_fact", "Task-2.3"],
	},
	{
		id: "ma-q4",
		scenario: "multi-agent-research",
		domain: "D1",
		tasks: ["1.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Coordinator needs findings from three subagents: (1) web search for current statistics, (2) document analysis for historical context, (3) a second web search for regulatory information. How should the coordinator invoke them?",
		choices: [
			{ key: "A", text: "In sequence across three separate responses: Task #1 (await), Task #2 (await), Task #3." },
			{ key: "B", text: "All three in a single coordinator response, as three separate Task tool calls. Coordinator awaits all three summaries before proceeding." },
			{ key: "C", text: "Tasks #1 and #2 in response 1, Task #3 in response 2 after #2 completes." },
			{ key: "D", text: "Invoke Task #1, then have it invoke Task #2 directly, then Task #3." },
		],
		correct: "B",
		explanation:
			"Parallel spawning = multiple Task calls in a single coordinator response. Preserves parallelism and respects hub-and-spoke (all routing through coordinator).",
		distractorRationales: {
			A: "Sequential across turns; loses parallelism.",
			C: "Splits across two responses; loses parallelism.",
			D: "Subagent-to-subagent invocation violates hub-and-spoke.",
		},
		studyTags: ["parallel-spawning", "hub-and-spoke", "Task-1.3"],
	},
	{
		id: "ma-q5",
		scenario: "multi-agent-research",
		domain: "D1",
		tasks: ["1.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Coordinator completed web-search phase (5 findings with URLs and dates). Now it invokes synthesis subagent. What should the synthesis prompt include?",
		choices: [
			{ key: "A", text: "A summary: 'Web search found 5 findings related to renewable energy. Proceed to synthesize.'" },
			{ key: "B", text: "Full structured findings: each with claim, source URL, publication date, excerpt — in structured format." },
			{ key: "C", text: "Just the URLs, no excerpts or dates (to save tokens)." },
			{ key: "D", text: "A high-level narrative summary of the web findings (coordinator writes a paragraph)." },
		],
		correct: "B",
		explanation:
			"Synthesis needs complete structured findings with metadata to preserve attribution through synthesis into the final report.",
		distractorRationales: {
			A: "Summary loses attribution; synthesis can't cite sources.",
			C: "URLs without dates/excerpts prevent proper conflict detection and citation.",
			D: "Narrative converts structured data to prose; synthesis can't extract citations.",
		},
		studyTags: ["context-passing", "claim-source-mappings", "Task-1.3"],
	},
	{
		id: "ma-q6",
		scenario: "multi-agent-research",
		domain: "D5",
		tasks: ["5.6"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Two sources give conflicting statistics: Source A (2024 report) says 'unemployment 3.8%,' Source B (2023 report) says 'unemployment 4.2%.' Synthesis needs to report this. Best approach?",
		choices: [
			{ key: "A", text: "Pick Source A (newer data) and ignore Source B." },
			{ key: "B", text: "Average them: 'approximately 4.0%.'" },
			{ key: "C", text: "Annotate both with publication dates: 'Source A (2024) reports 3.8%; Source B (2023) reports 4.2%. The difference reflects year-over-year change.'" },
			{ key: "D", text: "Report only the statistic with higher confidence; drop the other." },
		],
		correct: "C",
		explanation:
			"Include both with publication dates so readers understand whether the difference is temporal or methodological. Don't suppress information.",
		distractorRationales: {
			A: "Loses data and the trend.",
			B: "Invents a value not in any source.",
			D: "Confidence scores are often poorly calibrated; loses information unnecessarily.",
		},
		studyTags: ["conflict-handling", "publication-dates", "Task-5.6"],
	},
	{
		id: "ma-q7",
		scenario: "multi-agent-research",
		domain: "D1",
		tasks: ["1.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "A coordinator researches 'contemporary art movements.' It decomposes into: (1) 'abstract expressionism,' (2) 'pop art.' Final report covers only those two, omitting surrealism, color field, constructivism, kinetic art. Which is the root cause?",
		choices: [
			{ key: "A", text: "Web-search-agent timed out on several queries." },
			{ key: "B", text: "Coordinator's task decomposition was too narrow for a broad topic." },
			{ key: "C", text: "Synthesis agent arbitrarily dropped findings." },
			{ key: "D", text: "Document-analysis-agent returned empty results for the omitted movements." },
		],
		correct: "B",
		explanation:
			"Same root cause as Q1: narrow decomposition for a broad topic. Coordinator chose two specific movements without identifying all major categories.",
		distractorRationales: {
			A: "Timeout would surface as an error; narrow decomposition is the issue.",
			C: "Synthesis can only synthesize findings it receives.",
			D: "Document agent wasn't asked to analyze those movements.",
		},
		studyTags: ["narrow-decomposition", "Task-1.2"],
	},
	{
		id: "ma-q8",
		scenario: "multi-agent-research",
		domain: "D5",
		tasks: ["5.3"],
		mode: "canonical",
		difficulty: "hard",
		stem: "Web-search-agent reports a timeout on one query. Document-analysis-agent returns a file-not-found error on another. Both currently return generic 'error' statuses. How should subagents categorize these errors to enable coordinator recovery?",
		choices: [
			{ key: "A", text: "Both should return errorCategory: 'transient', isRetryable: true so coordinator retries both." },
			{ key: "B", text: "Timeout is transient (retry); file-not-found is validation (don't retry, escalate). Return different errorCategory values and let coordinator decide recovery per category." },
			{ key: "C", text: "Both are non-retryable; return isRetryable: false and propagate immediately." },
			{ key: "D", text: "Return isRetryable: false for both; retrying prevents finding alternative sources." },
		],
		correct: "B",
		explanation:
			"Task 2.2: error categories (transient, validation, business, permission) enable coordinator decisions. Timeout is transient; file-not-found is validation.",
		distractorRationales: {
			A: "File-not-found is not transient; retrying won't help.",
			C: "Transient errors warrant local retry before propagation.",
			D: "Distinguishing error types is the whole point of structured errors.",
		},
		studyTags: ["error-categories", "transient-vs-validation", "Task-5.3"],
	},
	{
		id: "ma-q9",
		scenario: "multi-agent-research",
		domain: "D2",
		tasks: ["2.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Synthesis subagent has 18 tools: WebSearch, WebFetch, Read, Glob, Grep, bash, verify_fact, summarize_document, extract_entities, cross_reference_sources, etc. It misuses tools (searches for new sources instead of integrating). Root cause?",
		choices: [
			{ key: "A", text: "System prompt doesn't explicitly forbid new searches." },
			{ key: "B", text: "Tool overload: too many tools causes model uncertainty about tool selection. Restrict to 4-5 tools per role. Synthesis should have only a scoped verification tool." },
			{ key: "C", text: "Subagent model is too weak (Haiku instead of Sonnet)." },
			{ key: "D", text: "Synthesis needs a more detailed output format." },
		],
		correct: "B",
		explanation:
			"Task 2.3: too many tools degrade tool selection. Synthesis role is narrow: integrate findings, preserve attribution, flag conflicts.",
		distractorRationales: {
			A: "System prompt can influence but won't fully override tool overload.",
			C: "Model weakness doesn't cause tool misuse; overload does.",
			D: "Output format doesn't affect which tools are invoked.",
		},
		studyTags: ["tool-overload", "scoped-tools", "Task-2.3"],
	},
	{
		id: "ma-q10",
		scenario: "multi-agent-research",
		domain: "D5",
		tasks: ["5.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Document-analysis-agent reads document X. File not found (disk I/O error). Should the subagent:",
		choices: [
			{ key: "A", text: "Retry the Read call with exponential backoff locally. If success, continue. If 3 retries fail, propagate structured error context to coordinator." },
			{ key: "B", text: "Immediately propagate error to coordinator without retrying." },
			{ key: "C", text: "Return empty results as success (assume the document is not essential)." },
			{ key: "D", text: "Terminate the entire workflow." },
		],
		correct: "A",
		explanation:
			"Local recovery for transient failures; propagate structured error context if local retry fails.",
		distractorRationales: {
			B: "Skip local recovery; some transient failures are recoverable.",
			C: "Suppresses error; coordinator can't account for missing data.",
			D: "Single failure doesn't terminate workflow; coordinator decides impact.",
		},
		studyTags: ["local-recovery", "error-propagation", "Task-5.3"],
	},
	{
		id: "ma-q11",
		scenario: "multi-agent-research",
		domain: "D1",
		tasks: ["1.2"],
		mode: "gotcha",
		difficulty: "medium",
		stem: "A coordinator notices its subagents return inconsistent findings depending on which subagent runs first. The coordinator wants to enforce that web-search-agent always runs before document-analysis-agent so context flows linearly. Best architecture?",
		choices: [
			{ key: "A", text: "Configure web-search-agent to invoke document-analysis-agent directly when it finishes — peer-to-peer chaining." },
			{ key: "B", text: "Keep hub-and-spoke routing through coordinator; coordinator owns ordering and explicitly invokes document-analysis-agent after web-search-agent returns." },
			{ key: "C", text: "Run all subagents in parallel and discard inconsistent findings via consensus." },
			{ key: "D", text: "Switch to a fixed sequential pipeline: web-search → document-analysis → synthesis." },
		],
		correct: "B",
		explanation:
			"Hub-and-spoke is the canonical pattern. Coordinator owns ordering and gap detection. Peer-to-peer invocation breaks observability and error handling.",
		distractorRationales: {
			A: "Peer-to-peer violates hub-and-spoke; loses observability and error handling.",
			C: "Consensus suppresses real findings missed in some runs.",
			D: "Fixed pipelines lose iterative refinement and gap detection.",
		},
		studyTags: ["hub-and-spoke", "no-peer-to-peer", "Task-1.2"],
	},
];
