import type { CertQuestion } from "./cert-types";

// Scenario 6: Structured Data Extraction
export const EXTRACTION_QUESTIONS: CertQuestion[] = [
	{
		id: "ex-q1",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You're extracting purchase order data. Schema marks po_number, vendor_name, line_items, and total_amount as required. The system hallucinates po_number values when the source doesn't include one. Most effective fix?",
		choices: [
			{ key: "A", text: "Add a validation step that flags 'suspiciously invented' po_numbers." },
			{ key: "B", text: "Change po_number from required to optional/nullable; accept null when genuinely absent." },
			{ key: "C", text: "Increase model temperature to retry with more creativity." },
			{ key: "D", text: "Mark po_number as required but add a few-shot example showing extraction when PO is missing." },
		],
		correct: "B",
		explanation:
			"Required + absent info = fabrication. Making fields optional/nullable lets the model return null, preserving accuracy.",
		distractorRationales: {
			A: "Validation can flag but can't prevent fabrication.",
			C: "Higher temperature increases hallucination, not accuracy.",
			D: "Required fields still force a value even with examples.",
		},
		studyTags: ["nullable-fields", "fabrication-prevention", "Task-4.3"],
	},
	{
		id: "ex-q2",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You receive varied financial documents (invoices, POs, credit memos, receipts). Document type is not pre-labeled. You have three extraction schemas. Which tool_choice setting ensures structured output while letting the model pick the right schema?",
		choices: [
			{ key: "A", text: "tool_choice: 'auto' with all three tools available." },
			{ key: "B", text: "tool_choice: 'any' with all three tools available." },
			{ key: "C", text: "tool_choice forced to the first tool; handle failures by retrying with the next." },
			{ key: "D", text: "tool_choice: 'auto' with a routing classifier that pre-selects the schema." },
		],
		correct: "B",
		explanation:
			"'any' forces a tool call but lets the model choose. Guarantees structured output for unknown doc types with multiple schemas.",
		distractorRationales: {
			A: "'auto' allows conversational text instead of tool call.",
			C: "Forced selection doesn't allow tool switching; wastes attempts.",
			D: "Adds unnecessary complexity; 'any' handles natively.",
		},
		studyTags: ["tool_choice", "any-mode", "Task-4.3"],
	},
	{
		id: "ex-q3",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Extraction returned: stated_total = 1500, calculated_total = 1480, conflict_detected = true. You retry with: 'Your calculated total ($1480) does not match stated total ($1500). Please correct.' Why will this likely FAIL?",
		choices: [
			{ key: "A", text: "Model is confident in line-item extraction; won't second-guess." },
			{ key: "B", text: "Discrepancy is in the source document, not the model's extraction. Retry can't fix source data." },
			{ key: "C", text: "Error message isn't specific enough; add original invoice text." },
			{ key: "D", text: "Model needs higher temperature to explore alternatives." },
		],
		correct: "B",
		explanation:
			"If source has inconsistent totals, retrying the model won't change source data. Flag conflict_detected=true and route to human review.",
		distractorRationales: {
			A: "The issue is source data, not model stubbornness.",
			C: "Adding text helps with FORMAT errors, not SOURCE data errors.",
			D: "Higher temperature increases hallucination.",
		},
		studyTags: ["retry-futility", "source-vs-format", "Task-4.4"],
	},
	{
		id: "ex-q4",
		scenario: "structured-extraction",
		domain: "D5",
		tasks: ["5.5"],
		mode: "canonical",
		difficulty: "hard",
		stem: "Extraction system reports 93% aggregate accuracy across 10,000 documents. Segments: invoices (7000 @ 97%), contracts (2000 @ 82%), receipts (1000 @ 91%). You want to reduce human review. Safest decision?",
		choices: [
			{ key: "A", text: "Reduce review across all types to 20% random sampling (aggregate accuracy supports it)." },
			{ key: "B", text: "Continue 100% review on contracts (82% unacceptable); reduce to 30% sampling on invoices (97%); reduce to 50% on receipts (91%)." },
			{ key: "C", text: "Remove contracts from automated extraction; route all to human pre-review; scale back sampling on invoices and receipts per segment accuracy." },
			{ key: "D", text: "Increase model temperature and retrain extraction prompt to improve contract accuracy, then revisit." },
		],
		correct: "B",
		explanation:
			"Segment by document type; validate per-segment before reducing review. Contracts at 82% = 1 in 5 wrong; can't automate.",
		distractorRationales: {
			A: "Relies on aggregate (hides segment failures).",
			C: "Over-corrects contracts; maybe fixable with prompt improvements.",
			D: "Temperature changes don't reliably improve accuracy.",
		},
		studyTags: ["per-segment-accuracy", "stratified-sampling", "Task-5.5"],
	},
	{
		id: "ex-q5",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.3"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You're extracting key facts from legal documents using a single extract_facts tool. Pipeline requires structured JSON for every document. With tool_choice: 'auto', the model occasionally returns conversational text like 'I cannot extract facts because this document is in an unusual language.' Most reliable change?",
		choices: [
			{ key: "A", text: "Keep 'auto' and add a few-shot example showing extraction from unusual-language documents." },
			{ key: "B", text: "Change to tool_choice: 'any'." },
			{ key: "C", text: "Change to forced selection: tool_choice: { type: 'tool', name: 'extract_facts' }." },
			{ key: "D", text: "Increase max_tokens so the model has room to call the tool after explaining." },
		],
		correct: "C",
		explanation:
			"Forced selection is the canonical mechanism for guaranteeing the model calls a specific named tool. With one tool and mandatory structure, forced is most precise.",
		distractorRationales: {
			A: "'auto' is permitted to return text regardless of examples.",
			B: "'any' happens to produce the same result with one tool but is wrong mechanism for 'must call THIS tool' — fragile if a second tool is added.",
			D: "max_tokens is unrelated to tool-call requirement.",
		},
		studyTags: ["tool_choice-forced", "Task-4.3"],
	},
	{
		id: "ex-q6",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.5"],
		mode: "canonical",
		difficulty: "medium",
		stem: "You need to extract data from 50,000 invoices. Results needed for nightly reconciliation at 2 AM, 30-min SLA. Approach that minimizes cost while meeting SLA?",
		choices: [
			{ key: "A", text: "Use sync API to ensure results complete within 30 minutes." },
			{ key: "B", text: "Use Message Batches API; submit at 1 PM the previous day to give 13-hour buffer before 2 AM." },
			{ key: "C", text: "Use sync for a sample of 500 invoices; batch the rest." },
			{ key: "D", text: "Use Message Batches API with a 2-hour timeout fallback to sync API." },
		],
		correct: "B",
		explanation:
			"Batch saves 50%, fits within 24-hour window; the workload is non-blocking (nightly).",
		distractorRationales: {
			A: "Sync is more expensive and unnecessary for non-blocking.",
			C: "Hybrid approach is over-complex.",
			D: "Batch has no guaranteed latency SLA; timeouts on batch don't exist.",
		},
		studyTags: ["batch-api", "non-blocking", "Task-4.5"],
	},
	{
		id: "ex-q7",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.2"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Your extraction system struggles with different invoice layouts: inline descriptions, tables, embedded narrative prose. Accuracy varies by format. Most effective?",
		choices: [
			{ key: "A", text: "Increase model temperature to encourage creative parsing." },
			{ key: "B", text: "Add few-shot examples explicitly covering each format variance (inline, tabular, narrative) showing extraction for each." },
			{ key: "C", text: "Refine the prompt with detailed format-parsing instructions for each variant." },
			{ key: "D", text: "Use separate fine-tuned models for each format; route by format first." },
		],
		correct: "B",
		explanation:
			"Few-shot examples are the most effective technique for format variance. Concrete examples teach generalization better than instructions.",
		distractorRationales: {
			A: "Temperature increases randomness, not accuracy.",
			C: "Detailed instructions help but are less effective than few-shot.",
			D: "Over-engineers; few-shot solves it without fine-tuning.",
		},
		studyTags: ["few-shot", "format-variance", "Task-4.2"],
	},
	{
		id: "ex-q8",
		scenario: "structured-extraction",
		domain: "D5",
		tasks: ["5.5"],
		mode: "canonical",
		difficulty: "hard",
		stem: "You labeled 200 invoices: 'high confidence' had 3 errors out of 100; 'medium confidence' had 40 errors out of 50; 'low confidence' had 45 errors out of 50. Goal: minimize review while keeping error rate under 5%. Right routing policy?",
		choices: [
			{ key: "A", text: "Route all 'low' and 'medium' to human review; auto-accept 'high' (3% error, under 5%)." },
			{ key: "B", text: "Route only 'low' to human review; sample 'medium' at 50%." },
			{ key: "C", text: "Auto-accept 'high' and 'medium'; route 'low'." },
			{ key: "D", text: "Route all to human review; confidence scores aren't reliable." },
		],
		correct: "A",
		explanation:
			"Calibrate to labeled data: 'high' = 3% error (acceptable), 'medium' = 80% error (way above threshold), 'low' = 90% error.",
		distractorRationales: {
			B: "Misses calibration of medium (80% error is unacceptable).",
			C: "'medium' clearly has high error rate.",
			D: "Abandons calibration prematurely.",
		},
		studyTags: ["confidence-calibration", "labeled-validation", "Task-5.5"],
	},
	{
		id: "ex-q9",
		scenario: "structured-extraction",
		domain: "D5",
		tasks: ["5.6"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Annual revenue extracted from three credible sources: earnings report says $10M, audited financials say $9.8M, investor presentation says $10.2M. How to report?",
		choices: [
			{ key: "A", text: "Pick the audited figure ($9.8M) as most authoritative." },
			{ key: "B", text: "Average the three ($10M); record extraction confidence as 'medium.'" },
			{ key: "C", text: "Annotate all three with sources, publication dates, methodologies; note the conflict; let downstream systems decide reconciliation." },
			{ key: "D", text: "Flag as 'conflict detected'; discard all three; manually investigate." },
		],
		correct: "C",
		explanation:
			"Preserve provenance and uncertainty. Don't arbitrarily pick or invent values.",
		distractorRationales: {
			A: "Loses uncertainty and explanation.",
			B: "Invents a value not in any source (introduces hallucination).",
			D: "Over-escalates; the conflict is informative, not an error.",
		},
		studyTags: ["provenance", "conflict-attribution", "Task-5.6"],
	},
	{
		id: "ex-q10",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.4"],
		mode: "canonical",
		difficulty: "medium",
		stem: "Your extraction system marks 5% of fields as 'unclear' or 'low confidence,' routing to human review. Humans find that 95% of these flagged extractions are actually correct. The system is over-flagging. To improve, prioritize?",
		choices: [
			{ key: "A", text: "Increase model temperature to reduce conservatism." },
			{ key: "B", text: "Analyze detected_pattern fields to understand which constructs trigger dismissals; refine few-shot examples for those patterns." },
			{ key: "C", text: "Remove the confidence routing entirely; auto-accept all extractions." },
			{ key: "D", text: "Retrain the model with higher confidence thresholds." },
		],
		correct: "B",
		explanation:
			"Use detected_pattern field to understand WHY the model flagged. Refine few-shot examples for those patterns.",
		distractorRationales: {
			A: "Temperature increases hallucination.",
			C: "Removes safety mechanism.",
			D: "Not practical without retraining; refining few-shot is the documented fix.",
		},
		studyTags: ["detected_pattern", "FP-dismissal", "Task-4.4"],
	},
	{
		id: "ex-q11",
		scenario: "structured-extraction",
		domain: "D4",
		tasks: ["4.3"],
		mode: "synthesis",
		difficulty: "hard",
		stem: "You're designing an invoice extraction tool that supports both USD-only invoices today and unknown future currencies. You also want to flag ambiguous extractions for human review without breaking the schema. Which combination is correct?",
		choices: [
			{ key: "A", text: "currency is a free-text string; extraction_confidence is a free-text string. Maximum flexibility." },
			{ key: "B", text: "currency: enum [USD, EUR, GBP, other] + currency_detail string for 'other'; extraction_confidence: enum [high, medium, low, unclear]. Extensible without breakage; 'unclear' signals human review without forced guessing." },
			{ key: "C", text: "currency: required string with regex validation; extraction_confidence: integer 0–100." },
			{ key: "D", text: "currency: enum [USD]; extraction_confidence: enum [high, medium, low]. Tight today, expand schema when needed." },
		],
		correct: "B",
		explanation:
			"Enums + 'other' + detail string enable safe extensibility. 'unclear' enum value signals ambiguous cases for human review.",
		distractorRationales: {
			A: "Free-text strings allow inconsistent values; no validation.",
			C: "Confidence as integer is harder to calibrate than calibrated enum buckets.",
			D: "Tight enum forces schema changes for new currencies; no 'unclear' option.",
		},
		studyTags: ["enum-other-detail", "unclear-value", "Task-4.3"],
	},
];
